import { useRegisterSW } from "virtual:pwa-register/react";

/** Registers the service worker generated by vite-plugin-pwa (registerType: "autoUpdate" —
 * a new version takes over and reloads silently, no user prompt). No-op during SSR and in
 * dev (devOptions.enabled is false in vite.config.ts). Mount once near the app root. */
export function PwaUpdater() {
  useRegisterSW();
  return null;
}
