/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BodyRouteImport } from './routes/body'
import { Route as DietRouteImport } from './routes/diet'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TestRouteImport } from './routes/test'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as VideoCoachRouteImport } from './routes/video-coach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoCoachRoute = VideoCoachRouteImport.update({
  id: '/video-coach',
  path: '/video-coach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/diet': typeof DietRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/highlights': typeof HighlightsRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test': typeof TestRoute
  '/training': typeof TrainingRoute
  '/video-coach': typeof VideoCoachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/diet': typeof DietRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/highlights': typeof HighlightsRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test': typeof TestRoute
  '/training': typeof TrainingRoute
  '/video-coach': typeof VideoCoachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/diet': typeof DietRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/highlights': typeof HighlightsRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/test': typeof TestRoute
  '/training': typeof TrainingRoute
  '/video-coach': typeof VideoCoachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body'
    | '/diet'
    | '/forgot-password'
    | '/highlights'
    | '/login'
    | '/matches'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/test'
    | '/training'
    | '/video-coach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/body'
    | '/diet'
    | '/forgot-password'
    | '/highlights'
    | '/login'
    | '/matches'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/test'
    | '/training'
    | '/video-coach'
  id:
    | '__root__'
    | '/'
    | '/body'
    | '/diet'
    | '/forgot-password'
    | '/highlights'
    | '/login'
    | '/matches'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/test'
    | '/training'
    | '/video-coach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyRoute: typeof BodyRoute
  DietRoute: typeof DietRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HighlightsRoute: typeof HighlightsRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestRoute: typeof TestRoute
  TrainingRoute: typeof TrainingRoute
  VideoCoachRoute: typeof VideoCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-coach': {
      id: '/video-coach'
      path: '/video-coach'
      fullPath: '/video-coach'
      preLoaderRoute: typeof VideoCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyRoute: BodyRoute,
  DietRoute: DietRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HighlightsRoute: HighlightsRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestRoute: TestRoute,
  TrainingRoute: TrainingRoute,
  VideoCoachRoute: VideoCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
